# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    # Ignore errors from these functions (common patterns)
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*github.com/spf13/cobra.Command).MarkFlagRequiredSlice
  
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - unmarshal
      - unreachable
      - unusedresult
  
  goimports:
    local-prefixes: github.com/aqua-io/aqua-service-controller
  
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
    
    # Exclude generated files
    - path: zz_generated
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
