# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/cobra.Command).MarkFlagRequiredSlice
    
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - copylocks
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - unmarshal
        - unreachable
        - unusedresult
    
    misspell:
      locale: US
