//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextRef) DeepCopyInto(out *ContextRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextRef.
func (in *ContextRef) DeepCopy() *ContextRef {
	if in == nil {
		return nil
	}
	out := new(ContextRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratedPodInfo) DeepCopyInto(out *MigratedPodInfo) {
	*out = *in
	in.MigratedAt.DeepCopyInto(&out.MigratedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratedPodInfo.
func (in *MigratedPodInfo) DeepCopy() *MigratedPodInfo {
	if in == nil {
		return nil
	}
	out := new(MigratedPodInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetMigration) DeepCopyInto(out *StatefulSetMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetMigration.
func (in *StatefulSetMigration) DeepCopy() *StatefulSetMigration {
	if in == nil {
		return nil
	}
	out := new(StatefulSetMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulSetMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetMigrationList) DeepCopyInto(out *StatefulSetMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatefulSetMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetMigrationList.
func (in *StatefulSetMigrationList) DeepCopy() *StatefulSetMigrationList {
	if in == nil {
		return nil
	}
	out := new(StatefulSetMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulSetMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetMigrationSpec) DeepCopyInto(out *StatefulSetMigrationSpec) {
	*out = *in
	out.SourceCluster = in.SourceCluster
	out.DestCluster = in.DestCluster
	if in.StorageClassMapping != nil {
		in, out := &in.StorageClassMapping, &out.StorageClassMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VolumeDetachTimeout != nil {
		in, out := &in.VolumeDetachTimeout, &out.VolumeDetachTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PodReadyTimeout != nil {
		in, out := &in.PodReadyTimeout, &out.PodReadyTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetMigrationSpec.
func (in *StatefulSetMigrationSpec) DeepCopy() *StatefulSetMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulSetMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetMigrationStatus) DeepCopyInto(out *StatefulSetMigrationStatus) {
	*out = *in
	if in.MigratedPods != nil {
		in, out := &in.MigratedPods, &out.MigratedPods
		*out = make([]MigratedPodInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.PreservedPVs != nil {
		in, out := &in.PreservedPVs, &out.PreservedPVs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetMigrationStatus.
func (in *StatefulSetMigrationStatus) DeepCopy() *StatefulSetMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulSetMigrationStatus)
	in.DeepCopyInto(out)
	return out
}
